# Generated by Django 6.0.3 on 2026-04-05 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('view_patients', 'View Patients'), ('add_patients', 'Add Patients'), ('edit_patients', 'Edit Patients'), ('delete_patients', 'Delete Patients'), ('view_medical_records', 'View Medical Records'), ('add_medical_records', 'Add Medical Records'), ('edit_medical_records', 'Edit Medical Records'), ('view_appointments', 'View Appointments'), ('manage_appointments', 'Manage Appointments'), ('view_prescriptions', 'View Prescriptions'), ('create_prescriptions', 'Create Prescriptions'), ('view_lab_results', 'View Lab Results'), ('manage_lab_results', 'Manage Lab Results'), ('view_users', 'View Users'), ('manage_users', 'Manage Users'), ('view_reports', 'View Reports'), ('manage_billing', 'Manage Billing')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('lab_technician', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('patient', 'Patient')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='userauths.role'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='userauths.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='userauths.role')),
            ],
            options={
                'ordering': ['role', 'permission'],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
