# Generated by Django 6.0.3 on 2026-04-06 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_permission_role_user_created_by_user_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('opd', 'Out-Patient Department (OPD)'), ('ipd', 'In-Patient Department (IPD)'), ('emergency', 'Emergency / Casualty'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('radiology', 'Radiology / Imaging'), ('surgery', 'Surgery'), ('maternity', 'Maternity / Obstetrics'), ('pediatrics', 'Pediatrics'), ('dental', 'Dental'), ('eye_clinic', 'Eye Clinic / Ophthalmology'), ('physiotherapy', 'Physiotherapy'), ('records', 'Medical Records'), ('admin', 'Administration'), ('other', 'Other')], max_length=50)),
                ('head_of_department', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['hospital__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='District code', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['region__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Region code e.g. WR, GA', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('view_patients', 'View Patients'), ('add_patients', 'Add Patients'), ('edit_patients', 'Edit Patients'), ('delete_patients', 'Delete Patients'), ('view_medical_records', 'View Medical Records'), ('add_medical_records', 'Add Medical Records'), ('edit_medical_records', 'Edit Medical Records'), ('view_appointments', 'View Appointments'), ('manage_appointments', 'Manage Appointments'), ('view_prescriptions', 'View Prescriptions'), ('create_prescriptions', 'Create Prescriptions'), ('view_lab_results', 'View Lab Results'), ('manage_lab_results', 'Manage Lab Results'), ('view_users', 'View Users'), ('manage_users', 'Manage Users'), ('view_reports', 'View Reports'), ('manage_billing', 'Manage Billing'), ('manage_hospitals', 'Manage Hospitals'), ('manage_districts', 'Manage Districts'), ('manage_regions', 'Manage Regions'), ('view_national_data', 'View National Data'), ('view_district_data', 'View District Data'), ('view_hospital_data', 'View Hospital Data'), ('manage_departments', 'Manage Departments')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ministry_admin', 'Ministry Administrator'), ('district_admin', 'District Administrator'), ('hospital_admin', 'Hospital Administrator'), ('admin', 'System Administrator'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('lab_technician', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('patient', 'Patient')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='userauths.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.ForeignKey(blank=True, help_text='For district admins', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_staff', to='userauths.district'),
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(help_text='Hospital registration code', max_length=30, unique=True)),
                ('hospital_type', models.CharField(choices=[('teaching', 'Teaching Hospital'), ('regional', 'Regional Hospital'), ('district', 'District Hospital'), ('polyclinic', 'Polyclinic'), ('health_center', 'Health Center'), ('clinic', 'Clinic'), ('chps', 'CHPS Compound'), ('private', 'Private Hospital')], default='district', max_length=30)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bed_capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='userauths.district')),
            ],
            options={
                'ordering': ['district__region__name', 'district__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='userauths.hospital'),
        ),
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='userauths.hospital'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='userauths.region'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'hospital')},
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'region')},
        ),
    ]
