# Generated by Django 6.0.3 on 2026-04-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, help_text='District code', max_length=20, unique=True),
        ),
    ]
