# Generated by Django 6.0.3 on 2026-04-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_district_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, help_text='Region code e.g. WR, GA', max_length=20, unique=True),
        ),
    ]
