# Generated by Django 6.0.3 on 2026-04-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='code',
            field=models.CharField(blank=True, help_text='Hospital registration code', max_length=30, unique=True),
        ),
    ]
