# Generated by Django 6.0.3 on 2026-04-09 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_alter_hospital_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_code',
            field=models.CharField(blank=True, help_text='Auto-generated department code', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='head_user',
            field=models.ForeignKey(blank=True, help_text='Assigned department head user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='hospital',
            name='admin_user',
            field=models.ForeignKey(blank=True, help_text='Linked system user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_hospitals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='allow_external_access',
            field=models.BooleanField(default=False, help_text='Allow referral sharing'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ambulance_available',
            field=models.BooleanField(default=False, help_text='Ambulance available'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='National Admin who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='catchment_population',
            field=models.PositiveIntegerField(blank=True, help_text='Population served', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='chiefdom_ward',
            field=models.CharField(blank=True, help_text='Chiefdom or Ward', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='country',
            field=models.CharField(default='Sierra Leone', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='data_sharing_consent',
            field=models.BooleanField(default=False, help_text='National data exchange consent'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='date_registered',
            field=models.DateField(auto_now_add=True, help_text='System registration date', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='dhis2_code',
            field=models.CharField(blank=True, help_text='DHIS2 integration code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emergency_contact_line',
            field=models.CharField(blank=True, help_text='Ambulance/emergency line', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emergency_services',
            field=models.BooleanField(default=False, help_text='Emergency services available'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='facility_code',
            field=models.CharField(blank=True, help_text='Government/Ministry facility code', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='facility_manager',
            field=models.CharField(blank=True, help_text='Administrative head', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='facility_timezone',
            field=models.CharField(default='Africa/Freetown', help_text='Facility time zone', max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_admin_name',
            field=models.CharField(blank=True, help_text='Responsible administrator name', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='inpatient_services',
            field=models.BooleanField(default=False, help_text='Inpatient services available'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='laboratory_available',
            field=models.BooleanField(default=False, help_text='Laboratory available'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='level_of_care',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary')], default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='license_expiry_date',
            field=models.DateField(blank=True, help_text='License expiry date', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='license_number',
            field=models.CharField(blank=True, help_text='Government license number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='maternity_services',
            field=models.BooleanField(default=False, help_text='Maternity services available'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='medical_superintendent',
            field=models.CharField(blank=True, help_text='Head doctor / Medical Superintendent', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='operational_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_approval', 'Pending Approval'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='outpatient_services',
            field=models.BooleanField(default=True, help_text='Outpatient services available'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ownership_type',
            field=models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('ngo', 'NGO'), ('faith_based', 'Faith-based'), ('military', 'Military')], default='government', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital',
            name='patient_id_prefix',
            field=models.CharField(blank=True, help_text='Patient ID prefix e.g. LUN', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='pharmacy_available',
            field=models.BooleanField(default=False, help_text='Pharmacy available'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='radiology_available',
            field=models.BooleanField(default=False, help_text='Radiology/Imaging available'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='referral_level',
            field=models.BooleanField(default=False, help_text='Can receive referrals'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='reporting_facility_code',
            field=models.CharField(blank=True, help_text='National reporting ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='secondary_phone',
            field=models.CharField(blank=True, help_text='Secondary phone number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='supervising_authority',
            field=models.CharField(blank=True, help_text='e.g. District Health Office', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='surgery_services',
            field=models.BooleanField(default=False, help_text='Surgery services available'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='town_city',
            field=models.CharField(blank=True, help_text='Town or City name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='website',
            field=models.URLField(blank=True, help_text='Hospital website URL', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='working_hours',
            field=models.CharField(blank=True, help_text='e.g. 8:00 AM - 5:00 PM', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='head_of_department',
            field=models.CharField(blank=True, help_text='Department head name', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('opd', 'Out-Patient Department (OPD)'), ('ipd', 'In-Patient Department (IPD)'), ('emergency', 'Emergency / Casualty'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('radiology', 'Radiology / Imaging'), ('surgery', 'Surgery'), ('maternity', 'Maternity / Obstetrics'), ('pediatrics', 'Pediatrics'), ('dental', 'Dental'), ('eye_clinic', 'Eye Clinic / Ophthalmology'), ('physiotherapy', 'Physiotherapy'), ('records', 'Medical Records'), ('admin', 'Administration'), ('ward', 'Ward'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(blank=True, help_text='Full physical address', null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='bed_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Total number of beds'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='code',
            field=models.CharField(blank=True, help_text='Auto-generated facility ID', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, help_text='Official hospital email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('government_hospital', 'Government Hospital'), ('private_hospital', 'Private Hospital'), ('clinic', 'Clinic'), ('health_center', 'Health Center'), ('community_health_post', 'Community Health Post'), ('diagnostic_center', 'Diagnostic Center'), ('pharmacy_facility', 'Pharmacy Facility'), ('teaching_hospital', 'Teaching Hospital'), ('regional_hospital', 'Regional Hospital'), ('district_hospital', 'District Hospital'), ('polyclinic', 'Polyclinic')], default='district_hospital', max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS Latitude', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS Longitude', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(help_text='Official facility name', max_length=300),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary phone number', max_length=50, null=True),
        ),
    ]
