# Generated by Django 6.0.3 on 2026-04-16 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_department_department_code_department_head_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chiefdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='Chiefdom code', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiefdoms', to='userauths.district')),
            ],
            options={
                'ordering': ['district__region__name', 'district__name', 'name'],
                'unique_together': {('name', 'district')},
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='Town/City code', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chiefdom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='towns', to='userauths.chiefdom')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towns', to='userauths.district')),
            ],
            options={
                'ordering': ['district__region__name', 'district__name', 'name'],
                'unique_together': {('name', 'district')},
            },
        ),
    ]
