# Generated by Django 6.0.3 on 2026-04-20 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0010_chiefdom_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='level_of_care',
            field=models.CharField(choices=[('community', 'Community Health Post (MCH/First Aid)'), ('primary', 'Primary Health Center (PHU/CHC)'), ('secondary_district', 'Secondary - District Hospital'), ('secondary_regional', 'Secondary - Regional/County Hospital'), ('tertiary', 'Tertiary - National/Specialized Hospital'), ('teaching', 'Teaching/University Hospital'), ('specialized', 'Specialized Center (Cancer/Cardiac/Mental)'), ('diagnostic', 'Diagnostic/Imaging Center'), ('rehabilitation', 'Rehabilitation/Palliative Care Center')], default='primary', max_length=20),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='(No subject)', max_length=200)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted_by_sender', models.BooleanField(default=False)),
                ('is_deleted_by_recipient', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='userauths.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='userauths_m_recipie_23effe_idx'), models.Index(fields=['sender', '-created_at'], name='userauths_m_sender__647c4d_idx')],
            },
        ),
    ]
