# Generated by Django 6.0.3 on 2026-04-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_alter_hospital_level_of_care_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Receive email alerts for new messages'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Receive SMS alerts for new messages'),
        ),
    ]
