# Generated by Django 6.0.3 on 2026-04-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0012_user_email_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='messages/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds (for audio/video)', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio / Voice Note'), ('file', 'File')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
