# Generated by Django 6.0.3 on 2026-04-22 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0013_message_attachment_message_attachment_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, help_text='e.g. SLeSHI, Private', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, help_text='NIN / National Identification Number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=models.CharField(default='Sierra Leonean', max_length=100),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(help_text='Appointment date and time')),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('checked_in', 'Checked In'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Chief complaint / reason for visit')),
                ('notes', models.TextField(blank=True, help_text='Receptionist/staff notes')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When doctor started consultation', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='userauths.department')),
                ('doctor', models.ForeignKey(help_text='Assigned doctor', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='userauths.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='userauths.patient')),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['hospital', 'scheduled_at'], name='userauths_a_hospita_2e3a3e_idx'), models.Index(fields=['doctor', 'status'], name='userauths_a_doctor__1f9cc7_idx'), models.Index(fields=['patient', '-scheduled_at'], name='userauths_a_patient_d51bf7_idx'), models.Index(fields=['status', 'scheduled_at'], name='userauths_a_status_ac6518_idx')],
            },
        ),
    ]
