# Generated by Django 6.0.3 on 2026-04-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0014_alter_patient_insurance_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='chiefdom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='userauths.chiefdom'),
        ),
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='userauths.district'),
        ),
        migrations.AddField(
            model_name='patient',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='userauths.town'),
        ),
    ]
