# Generated by Django 6.0.3 on 2026-05-04 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0015_patient_chiefdom_patient_district_patient_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('outpatient', 'Outpatient (OPD)'), ('inpatient', 'Inpatient (IPD)'), ('emergency', 'Emergency'), ('follow_up', 'Follow-up'), ('referral', 'Referral'), ('routine_checkup', 'Routine Check-up')], default='outpatient', max_length=20)),
                ('chief_complaint', models.TextField(help_text='Primary reason for this visit')),
                ('visit_date', models.DateTimeField(help_text='Date and time of visit')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('triaged', 'Triaged'), ('waiting', 'Waiting for Doctor'), ('in_progress', 'In Consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('referred_out', 'Referred Out')], default='registered', max_length=20)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_notes', models.TextField(blank=True)),
                ('referred_to_doctor', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit', to='userauths.appointment')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='userauths.department')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_visits', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='userauths.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='userauths.patient')),
                ('referred_to_hospital', models.ForeignKey(blank=True, help_text='If patient referred elsewhere', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_visits', to='userauths.hospital')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_of_presenting_illness', models.TextField(blank=True, help_text='HPI — patient narrative')),
                ('diagnosis', models.TextField(help_text='Primary diagnosis')),
                ('secondary_diagnoses', models.TextField(blank=True, help_text='Additional / differential diagnoses')),
                ('clinical_findings', models.TextField(blank=True, help_text='Physical examination findings')),
                ('investigations_ordered', models.TextField(blank=True, help_text='Lab tests, imaging, etc. ordered')),
                ('investigation_results', models.TextField(blank=True, help_text='Results if available at visit')),
                ('treatment_plan', models.TextField(blank=True)),
                ('prescriptions', models.TextField(blank=True, help_text='Drugs prescribed — name, dose, frequency, duration')),
                ('procedures_done', models.TextField(blank=True, help_text='Minor procedures performed during visit')),
                ('patient_education', models.TextField(blank=True, help_text='Advice/education given to patient')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=False, help_text='Restrict to authorised staff only')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_notes', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_note', to='userauths.patientvisit')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, help_text='mmHg', null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, help_text='mmHg', null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='bpm', null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, help_text='breaths/min', null=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, help_text='SpO2 %', max_digits=4, null=True)),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, help_text='mmol/L', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='userauths.patientvisit')),
            ],
        ),
        migrations.AddIndex(
            model_name='patientvisit',
            index=models.Index(fields=['patient', '-visit_date'], name='userauths_p_patient_d0b00c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvisit',
            index=models.Index(fields=['hospital', '-visit_date'], name='userauths_p_hospita_6752e4_idx'),
        ),
        migrations.AddIndex(
            model_name='patientvisit',
            index=models.Index(fields=['doctor', 'status'], name='userauths_p_doctor__3642d7_idx'),
        ),
    ]
