# Generated by Django 6.0.3 on 2026-05-05 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0017_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='decline_reason',
            field=models.TextField(blank=True, help_text='Reason doctor declined the request'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_date',
            field=models.DateField(blank=True, help_text="Patient's preferred date", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_time_note',
            field=models.CharField(blank=True, help_text="Patient's preferred time note (e.g. morning)", max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Confirmed appointment date and time (set by doctor)', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Doctor Review'), ('scheduled', 'Scheduled'), ('declined', 'Declined'), ('checked_in', 'Checked In'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('appointment_confirmed', 'Appointment Confirmed'), ('appointment_declined', 'Appointment Declined'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_request', 'New Appointment Request'), ('general', 'General')], default='general', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='userauths.appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
