# Generated by Django 6.0.3 on 2026-05-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0019_doctoravailability_doctorunavailabledate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when consultation was started', null=True),
        ),
    ]
