# Generated by Django 6.0.3 on 2026-05-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0020_add_consultation_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_referral',
            field=models.BooleanField(default=False, help_text='True if this is a cross-hospital referral appointment'),
        ),
    ]
