# Generated by Django 6.0.3 on 2026-05-25 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0025_profile_nin_nationality_marital_certificate_license'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='userauths_a_patient_4b12d2_idx',
            old_name='userauths_a_patient_9c0b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='userauths_a_user_id_313a99_idx',
            old_name='userauths_a_user_id_8f0f3e_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='userauths_a_access__9ec116_idx',
            old_name='userauths_a_access_t_7a0e6e_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='userauths_a_outcome_9e1650_idx',
            old_name='userauths_a_outcome_d_7b1f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='userauths_a_created_168c10_idx',
            old_name='userauths_a_created_3c4d5e_idx',
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, help_text='When the prescription was dispensed', null=True),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, help_text='Pharmacist who dispensed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='is_dispensed',
            field=models.BooleanField(default=False, help_text='Marked true when pharmacist dispenses medication'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='pharmacy_note',
            field=models.TextField(blank=True, help_text='Pharmacist notes: substitutions, counselling, stock remarks'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('opd', 'Out-Patient Department (OPD)'), ('ipd', 'In-Patient Department (IPD)'), ('emergency', 'Emergency / Casualty'), ('laboratory', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('radiology', 'Radiology / Imaging'), ('surgery', 'Surgery'), ('maternity', 'Maternity / Obstetrics'), ('pediatrics', 'Pediatrics'), ('dental', 'Dental'), ('eye_clinic', 'Eye Clinic / Ophthalmology'), ('physiotherapy', 'Physiotherapy'), ('records', 'Medical Records'), ('admin', 'Administration'), ('triage', 'Triage'), ('ward', 'Ward'), ('other', 'Other')], max_length=50),
        ),
    ]
