# Generated by Django 6.0.3 on 2026-05-30 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0027_add_lab_inventory_mch_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Dispensing'), ('dispensed', 'Dispensed'), ('partial', 'Partially Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='General prescription notes / patient counselling')),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_note', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structured_prescription', to='userauths.clinicalnote')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_dispensed', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='userauths.hospital')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='userauths.patientvisit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(help_text='Drug name (free text fallback if not in inventory)', max_length=200)),
                ('strength', models.CharField(blank=True, help_text='e.g. 500mg', max_length=100)),
                ('dosage_form', models.CharField(blank=True, help_text='e.g. Tablet, Syrup', max_length=100)),
                ('dose', models.CharField(help_text='e.g. 1 tablet, 5ml', max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral (PO)'), ('iv', 'Intravenous (IV)'), ('im', 'Intramuscular (IM)'), ('sc', 'Subcutaneous (SC)'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('rectal', 'Rectal (PR)'), ('sublingual', 'Sublingual (SL)'), ('ophthalmic', 'Ophthalmic (Eye)'), ('otic', 'Otic (Ear)'), ('nasal', 'Nasal'), ('other', 'Other')], default='oral', max_length=20)),
                ('frequency', models.CharField(choices=[('once', 'Once (stat)'), ('od', 'Once daily (OD)'), ('bd', 'Twice daily (BD)'), ('tds', 'Three times daily (TDS)'), ('qid', 'Four times daily (QID)'), ('nocte', 'At night (Nocte)'), ('prn', 'As needed (PRN)'), ('weekly', 'Once weekly'), ('other', 'Other / See notes')], default='bd', max_length=20)),
                ('duration_days', models.PositiveIntegerField(blank=True, help_text='Duration in days', null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Total quantity to dispense')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions, e.g. take with food')),
                ('is_dispensed', models.BooleanField(default=False)),
                ('dispensed_qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drug', models.ForeignKey(blank=True, help_text='Link to inventory drug if available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='userauths.druginventory')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='userauths.prescription')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
