# Generated by Django 6.0.3 on 2026-05-30 02:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0028_prescription_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Male Medical Ward 1', max_length=200)),
                ('ward_type', models.CharField(choices=[('general_male', 'General Male Ward'), ('general_female', 'General Female Ward'), ('pediatric', 'Pediatric Ward'), ('maternity', 'Maternity Ward'), ('icu', 'Intensive Care Unit (ICU)'), ('nicu', 'Neonatal ICU'), ('surgical', 'Surgical Ward'), ('isolation', 'Isolation Ward'), ('private', 'Private Ward'), ('other', 'Other')], default='general_male', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Maximum beds in this ward')),
                ('floor', models.CharField(blank=True, help_text='e.g. 1st Floor', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('renovation', 'Under Renovation')], default='active', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='userauths.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='userauths.hospital')),
            ],
            options={
                'ordering': ['hospital__name', 'name'],
                'unique_together': {('hospital', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(help_text='e.g. A-01, Bed 3', max_length=50)),
                ('bed_type', models.CharField(choices=[('standard', 'Standard'), ('electric', 'Electric'), ('icu', 'ICU Bed'), ('pediatric', 'Pediatric Cot'), ('bassinet', 'Bassinet'), ('isolation', 'Isolation Bed'), ('delivery', 'Delivery Bed'), ('recovery', 'Recovery Bed'), ('other', 'Other')], default='standard', max_length=15)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning')], default='available', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Special equipment, isolation precautions, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='userauths.ward')),
            ],
            options={
                'ordering': ['ward__name', 'bed_number'],
                'unique_together': {('ward', 'bed_number')},
            },
        ),
        migrations.CreateModel(
            name='InpatientAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When patient was formally admitted to bed')),
                ('admission_notes', models.TextField(blank=True, help_text='Reason for admission, referral note, etc.')),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_type', models.CharField(blank=True, choices=[('discharged', 'Discharged — improved'), ('discharged_ama', 'Discharged — against medical advice'), ('transferred', 'Transferred to another facility'), ('referred', 'Referred to specialist'), ('absconded', 'Absconded'), ('died', 'Died'), ('other', 'Other')], max_length=20)),
                ('discharge_summary', models.TextField(blank=True, help_text='Final diagnosis, procedures, outcome')),
                ('discharge_medications', models.TextField(blank=True, help_text='Medications on discharge')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('admitted', 'Currently Admitted'), ('discharged', 'Discharged'), ('transferred', 'Transferred')], default='admitted', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_created', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='userauths.bed')),
                ('care_team', models.ManyToManyField(blank=True, help_text='Doctors and nurses assigned', related_name='admissions_care_team', to=settings.AUTH_USER_MODEL)),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges_done', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='userauths.hospital')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission', to='userauths.patientvisit')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='userauths.ward')),
            ],
            options={
                'ordering': ['-admission_date'],
                'indexes': [models.Index(fields=['hospital', 'status', '-admission_date'], name='userauths_i_hospita_dad532_idx'), models.Index(fields=['bed', 'status'], name='userauths_i_bed_id_71bc62_idx')],
            },
        ),
    ]
