# Generated by Django 6.0.3 on 2026-05-31 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0030_add_billing_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'Morning (6am–2pm)'), ('afternoon', 'Afternoon (2pm–10pm)'), ('night', 'Night (10pm–6am)')], default='morning', max_length=15)),
                ('note_date', models.DateField(default=django.utils.timezone.now)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, help_text='0–10 scale', null=True)),
                ('iv_fluids_given', models.TextField(blank=True)),
                ('oral_intake', models.TextField(blank=True)),
                ('urine_output', models.TextField(blank=True)),
                ('medications_given', models.TextField(blank=True)),
                ('wound_care', models.TextField(blank=True)),
                ('patient_education', models.TextField(blank=True)),
                ('nursing_assessment', models.TextField(blank=True, help_text='Subjective & objective findings')),
                ('nursing_plan', models.TextField(blank=True, help_text='Interventions and plan')),
                ('handover_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='userauths.inpatientadmission')),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_notes_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-note_date', '-created_at'],
            },
        ),
    ]
