# Generated by Django 6.0.3 on 2026-05-31 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0031_nursing_note'),
        ('userauths', '0034_insuranceclaim'),
    ]

    operations = [
    ]
