# Generated by Django 6.0.3 on 2026-06-05 17:45

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0035_merge_0031_nursing_note_0034_insuranceclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclaim',
            name='member_id',
            field=models.CharField(blank=True, help_text='Patient membership / policy number', max_length=100),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='provider_name',
            field=models.CharField(help_text='Insurance company / scheme name', max_length=200),
        ),
        migrations.CreateModel(
            name='MedicalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_id', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='SPEC', unique=True)),
                ('name', models.CharField(help_text='Specialty name', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the specialty', null=True)),
                ('category', models.CharField(choices=[('general_medicine', 'General Medicine'), ('surgery', 'Surgery'), ('obstetrics_gynecology', 'Obstetrics & Gynecology'), ('pediatrics', 'Pediatrics'), ('other_clinical', 'Other Clinical Specialties')], default='other_clinical', help_text='Specialty category', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Active status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_specialties', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Associated department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialties', to='userauths.department')),
            ],
            options={
                'verbose_name': 'Medical Specialty',
                'verbose_name_plural': 'Medical Specialties',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='specialties',
            field=models.ManyToManyField(blank=True, help_text='Medical specialties for doctors', related_name='doctors', to='userauths.medicalspecialty'),
        ),
    ]
