# Generated by Django 6.0.3 on 2026-06-07 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0036_alter_insuranceclaim_member_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('surgery', 'Surgery Department'), ('icu', 'ICU Department'), ('laboratory', 'Laboratory Department'), ('radiology', 'Radiology Department'), ('medical', 'Medical Department (General Medicine)'), ('dental', 'Dental Department'), ('physiotherapy', 'Physiotherapy Department'), ('ophthalmology', 'Ophthalmology Department'), ('ent', 'ENT Department'), ('psychiatry', 'Psychiatry Department'), ('ipd', 'In-Patient Department (IPD)'), ('opd', 'Out-Patient Department (OPD)'), ('pediatrics', 'Pediatrics Department'), ('emergency', 'Emergency / Casualty'), ('pharmacy', 'Pharmacy'), ('maternity', 'Maternity / Obstetrics'), ('records', 'Medical Records'), ('admin', 'Administration'), ('triage', 'Triage'), ('other', 'Other')], max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Full display name', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department Category',
                'verbose_name_plural': 'Department Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unit name (e.g., General Surgery, Hematology Lab)', max_length=200)),
                ('code', models.CharField(blank=True, help_text='Auto-generated unit code', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='userauths.departmentcategory')),
            ],
            options={
                'verbose_name': 'Department Unit',
                'verbose_name_plural': 'Department Units',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='HospitalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(blank=True, help_text='Auto-generated department code', max_length=50, unique=True)),
                ('head_of_department', models.CharField(blank=True, help_text='Department head name', max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location in hospital (e.g., Building A, Floor 2)', max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_construction', 'Under Construction'), ('temporarily_closed', 'Temporarily Closed')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_instances', to='userauths.departmentcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hospital_departments', to=settings.AUTH_USER_MODEL)),
                ('head_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_hospital_departments', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_departments', to='userauths.hospital')),
            ],
            options={
                'verbose_name': 'Hospital Department',
                'verbose_name_plural': 'Hospital Departments',
                'ordering': ['hospital__name', 'category__name'],
                'unique_together': {('hospital', 'category')},
            },
        ),
        migrations.CreateModel(
            name='HospitalDepartmentUnitInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(blank=True, help_text='Auto-generated unit instance code', max_length=50)),
                ('unit_head', models.CharField(blank=True, help_text='Unit head/supervisor name', max_length=300, null=True)),
                ('bed_capacity', models.PositiveIntegerField(default=0, help_text='Number of beds (if applicable)')),
                ('staff_count', models.PositiveIntegerField(default=0, help_text='Number of staff assigned')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, help_text='Specific location within department', max_length=200, null=True)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('non_operational', 'Non-Operational'), ('under_maintenance', 'Under Maintenance')], default='operational', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_instances', to='userauths.hospitaldepartment')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_instances', to='userauths.departmentunit')),
                ('unit_head_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital Department Unit Instance',
                'verbose_name_plural': 'Hospital Department Unit Instances',
                'ordering': ['hospital_department__hospital__name', 'hospital_department__category__name', 'unit__name'],
                'unique_together': {('hospital_department', 'unit')},
            },
        ),
    ]
